# logging-deploy.yml
# https://wbluke.tistory.com/39
name: cicd-makgol

on:
  push:
    branches: [ main ] # main branch로 push 될 때 실행됩니다.

env: # 새로 추가한 부분
  S3_BUCKET_NAME: makgol-deploy
  PROJECT_NAME: makgol

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Create Application Properties
        run: |
          echo "server.port=${{ secrets.SERVER_PORT }}" >> src/main/resources/application.properties
          echo "spring.datasource.driver-class-name=${{ secrets.SPRING_DATASOURCE_DRIVER_CLASS_NAME }}" >> src/main/resources/application.properties
          echo "spring.datasource.url=${{ secrets.SPRING_DATASOURCE_URL }}" >> src/main/resources/application.properties
          echo "spring.datasource.username=${{ secrets.SPRING_DATASOURCE_USERNAME }}" >> src/main/resources/application.properties
          echo "spring.datasource.password=${{ secrets.SPRING_DATASOURCE_PASSWORD }}" >> src/main/resources/application.properties
          echo "spring.mail.port=${{ secrets.SPRING_MAIL_PORT }}" >> src/main/resources/application.properties
          echo "spring.mail.host=${{ secrets.SPRING_MAIL_HOST }}" >> src/main/resources/application.properties
          echo "spring.mail.account=${{ secrets.SPRING_MAIL_ACCOUNT }}" >> src/main/resources/application.properties
          echo "spring.redis.host=${{ secrets.SPRING_REDIS_HOST }}" >> src/main/resources/application.properties
          echo "spring.redis.port=${{ secrets.SPRING_REDIS_PORT }}" >> src/main/resources/application.properties
          echo "jwt.secret.key=${{ secrets.JWT_SECRET_KEY }}" >> src/main/resources/application.properties
          echo "spring.security.oauth2.client.registration.kakao.clientId=${{ secrets.KAKAO_CLIENT_ID }}" >> src/main/resources/application.properties
          echo "spring.security.oauth2.client.registration.kakao.clientSecret=${{ secrets.KAKAO_CLIENT_SECRET }}" >> src/main/resources/application.properties
          echo "spring.security.oauth2.client.registration.naver.clientId=${{ secrets.NAVER_CLIENT_ID }}" >> src/main/resources/application.properties
          echo "spring.security.oauth2.client.registration.naver.clientSecret=${{ secrets.NAVER_CLIENT_SECRET }}" >> src/main/resources/application.properties

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Delete Uploaded File in S3
        run: aws s3 rm s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name makgol-CICD --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name develop --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip